"""schema initial

Revision ID: 719b309ce4d3
Revises: 
Create Date: 2026-08-27 19:56:54.551921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '719b309ce4d3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.String(), nullable=True),
    sa.Column('birth_date', sa.String(), nullable=True),
    sa.Column('family_history', sa.String(), nullable=True),
    sa.Column('medical_history', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_table('biopsies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_biopsies_id'), 'biopsies', ['id'], unique=False)
    op.create_table('extractions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('dzi_url', sa.String(), nullable=True),
    sa.Column('x', sa.Integer(), nullable=True),
    sa.Column('y', sa.Integer(), nullable=True),
    sa.Column('w', sa.Integer(), nullable=True),
    sa.Column('h', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('owner', sa.String(), nullable=True),
    sa.Column('prelevement_type', sa.String(), nullable=True),
    sa.Column('prelevement_date', sa.String(), nullable=True),
    sa.Column('block_number', sa.String(), nullable=True),
    sa.Column('fixation', sa.String(), nullable=True),
    sa.Column('slide_count', sa.Integer(), nullable=True),
    sa.Column('staining', sa.JSON(), nullable=True),
    sa.Column('macro_obs', sa.Text(), nullable=True),
    sa.Column('micro_obs', sa.Text(), nullable=True),
    sa.Column('histo_type', sa.String(), nullable=True),
    sa.Column('sbr_grade', sa.String(), nullable=True),
    sa.Column('margins', sa.String(), nullable=True),
    sa.Column('hormonal_receptors', sa.String(), nullable=True),
    sa.Column('diagnosis', sa.String(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('pathologist', sa.String(), nullable=True),
    sa.Column('validation_date', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extractions_id'), 'extractions', ['id'], unique=False)
    op.create_table('radiology_studies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('orthanc_study_id', sa.String(), nullable=True),
    sa.Column('modality', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('report', sa.Text(), nullable=True),
    sa.Column('annotations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_radiology_studies_id'), 'radiology_studies', ['id'], unique=False)
    op.create_table('drawings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('w', sa.Float(), nullable=True),
    sa.Column('h', sa.Float(), nullable=True),
    sa.Column('radius', sa.Float(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('points', sa.JSON(), nullable=True),
    sa.Column('author', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_drawings_id'), 'drawings', ['id'], unique=False)
    op.create_table('workflow_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('extraction_id', sa.Integer(), nullable=False),
    sa.Column('current_step', sa.String(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extraction_id'], ['extractions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_states_extraction_id'), 'workflow_states', ['extraction_id'], unique=True)
    op.create_index(op.f('ix_workflow_states_id'), 'workflow_states', ['id'], unique=False)
    op.create_table('workflow_step_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workflow_state_id', sa.Integer(), nullable=False),
    sa.Column('step', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('validated_at', sa.DateTime(), nullable=True),
    sa.Column('validated_by', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workflow_state_id'], ['workflow_states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workflow_state_id', 'step', name='uq_workflow_step')
    )
    op.create_index(op.f('ix_workflow_step_states_id'), 'workflow_step_states', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_step_states_workflow_state_id'), 'workflow_step_states', ['workflow_state_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_workflow_step_states_workflow_state_id'), table_name='workflow_step_states')
    op.drop_index(op.f('ix_workflow_step_states_id'), table_name='workflow_step_states')
    op.drop_table('workflow_step_states')
    op.drop_index(op.f('ix_workflow_states_id'), table_name='workflow_states')
    op.drop_index(op.f('ix_workflow_states_extraction_id'), table_name='workflow_states')
    op.drop_table('workflow_states')
    op.drop_index(op.f('ix_drawings_id'), table_name='drawings')
    op.drop_table('drawings')
    op.drop_index(op.f('ix_radiology_studies_id'), table_name='radiology_studies')
    op.drop_table('radiology_studies')
    op.drop_index(op.f('ix_extractions_id'), table_name='extractions')
    op.drop_table('extractions')
    op.drop_index(op.f('ix_biopsies_id'), table_name='biopsies')
    op.drop_table('biopsies')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    # ### end Alembic commands ###
